### ISSUE TITLE
http 500 error - The log file could not be created

### ISSUE THREAD

**Issue by moisesdfelix** [glpi-project/glpi#10241]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.5

### Bug description

The "Blank Screen" of the GLPI normally occurs due to some internal permission error, on the server side, using the browser's inspect option to confirm the error, in this case it is error 500 which is something very generic where the web server cannot handle the request, due to some unexpected condition.

### Relevant log output

```shell
2021-12-31 13:24:04] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot read - connection closed? in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php at line 116
  Backtrace :
  .../laminas/laminas-mail/src/Protocol/Imap.php:143 Laminas\Mail\Protocol\Imap->nextLine()
  .../laminas/laminas-mail/src/Protocol/Imap.php:262 Laminas\Mail\Protocol\Imap->nextTaggedLine()
  .../laminas/laminas-mail/src/Protocol/Imap.php:285 Laminas\Mail\Protocol\Imap->readLine()
  .../laminas/laminas-mail/src/Protocol/Imap.php:350 Laminas\Mail\Protocol\Imap->readResponse()
  .../laminas/laminas-mail/src/Protocol/Imap.php:811 Laminas\Mail\Protocol\Imap->requestAndResponse()
  ...or/laminas/laminas-mail/src/Storage/Imap.php:80 Laminas\Mail\Protocol\Imap->search()
  inc/mailcollector.class.php:1472                   Laminas\Mail\Storage\Imap->countMessages()
  inc/mailcollector.class.php:709                    MailCollector->getTotalMails()
  inc/mailcollector.class.php:1742                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2021-12-31 13:55:03] glpiphplog.ERROR: MailCollector::collect() in /var/www/html/glpi/inc/mailcollector.class.php line 689
An error occured trying to connect to collector. cannot read - connection closed? 
 #0 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(143): Laminas\Mail\Protocol\Imap->nextLine()
#1 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(262): Laminas\Mail\Protocol\Imap->nextTaggedLine(NULL)
#2 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(285): Laminas\Mail\Protocol\Imap->readLine(NULL, 'TAG1', true)
#3 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(350): Laminas\Mail\Protocol\Imap->readResponse('TAG1', true)
#4 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php(406): Laminas\Mail\Protocol\Imap->requestAndResponse('LOGIN', Array, true)
#5 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php(222): Laminas\Mail\Protocol\Imap->login('xpto...', 'xpto...')
#6 /var/www/html/glpi/inc/toolbox.class.php(2348): Laminas\Mail\Storage\Imap->__construct(Object(stdClass))
#7 /var/www/html/glpi/inc/mailcollector.class.php(1324): Toolbox::getMailServerStorageInstance('imap', Array)
#8 /var/www/html/glpi/inc/mailcollector.class.php(683): MailCollector->connect()
#9 /var/www/html/glpi/inc/mailcollector.class.php(1742): MailCollector->collect(6)
#10 /var/www/html/glpi/inc/crontask.class.php(943): MailCollector::cronMailgate(Object(CronTask))
#11 /var/www/html/glpi/front/cron.php(83): CronTask::launch(2, '5')
```

### Steps To reproduce

Form Selection > Open Call
![erro 500 glpi](https://user-images.githubusercontent.com/50854086/147882623-f2cf1225-949a-4e79-b41c-abfd4ee4de9a.png)
![solucao erro constante](https://user-images.githubusercontent.com/50854086/147882626-9543b34a-38bd-45c3-a6f7-ecc0f8613eea.png)
![erro constante glpi](https://user-images.githubusercontent.com/50854086/147882630-e98d0f81-e59a-43f7-8a10-40cfff546c8e.png)

![PrintScreen-2022_3](https://user-images.githubusercontent.com/50854086/147882847-8643ddce-a502-4c68-8021-3fb3b48ca191.png)

**Comment by moisesdfelix** [comment]
[https://i.ibb.co/806Hk24/erro-500-glpi.png](url)
Attached is the error 500

**Comment by cedric-anne** [comment]
Hi,

This kind of issues is often due to usage of the GLPI scripts/console (i.e. `front/cron.php`, `bin/console`, ...) using root user in CLI context.

Regards

**Comment by trasher** [comment]
This may also be a crontask ran using root user. Anyways, it's not a GLPI bug.

**Comment by moisesdfelix** [comment]
Thanks for the help cedric-anne, I'll put the user www-data to run cron
