### ISSUE TITLE
On Planning the "See schedule of people in my groups" without "See Personal Planning" gives permission denied

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12736]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When needed external or group calendars there is no way to see only those without the personal planning of each user. Actually:
-Personal: should be show only their own plannings
-Personal+Groups: should be shown everything in the group
-Group: should be show only group plannings excluding the personal plannings of the other users on the group, but it gives "permission denied"

By giving the link to the users it's possible to add the group calendar to the client, but it's not possible to be viewed as read-only into the GLPI

Excuse me it's not seem as bug, if it's not I'll proceed by requesting it as a feature request as I'm not good in twig yet..

### Relevant log output

```shell
access-errors.log
User ID: 841 tried to access or perform an action on /front/planning.php with insufficient rights. Additional information: User is missing the 1 (READ) right for planning
        Stack Trace:
                /var/www/html/glpi/src/Session.php:984 displayRightError()
                /var/www/html/glpi/front/planning.php:39 checkRight()
```

### Steps To reproduce

1. Go to Administration
2. Go to Pofiles
3. Select some profile
4. check the SEE SCHEDULE OF PEOPLE IN MY GROUPS
5. uncheck SEE PERSONNAL PLANNING
6. User logins and goes to Assictance -Planning
7. You don't have permission to perform this action.

### Your GLPI setup information

Information about system installation and configuration
GLPI 10.0.3 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

Plugins list
--
fields               Name: Additional fields              Version: 1.17.3     State: Installed / not activated                		Install Method: Marketplace 	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated                		Install Method: Marketplace 	datainjection        Name: Data injection                 Version: 2.12.0     State: Installed / not activated                		Install Method: Marketplace 	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated                		Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                  		Install Method: Marketplace 	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Installed / not activated                		Install Method: Marketplace 	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                  		Install Method: Marketplace 	itilcategorygroups   Name: ItilCategory Groups            Version: 2.5.1      State: Installed / not activated                		Install Method: Marketplace 	mreporting           Name: More Reporting                 Version: 1.8.1      State: Installed / not activated                		Install Method: Marketplace 	screenshot           Name: Screenshot                     Version: 2.0.1      State: Installed / not activated                		Install Method: Marketplace 	stab                 Name: Split Timeline Action Buttons  Version: 1.1.0      State: Enabled                                  		Install Method: Marketplace 	tag                  Name: Tag Management                 Version: 2.10.0     State: Enabled                                  		Install Method: Marketplace 	typology             Name: Typologies                     Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	yagp                 Name: yagp                           Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace

**Comment by dxdemetriou** [comment]
There is also another issue, somebody with read only permissions on "Planning", can delete a group event, even with the 403 forbidden:

==> access-errors.log <==
````
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-22 18:16:18 [15650@glpi-new]
User ID: 15650 tried to access or perform an action on /front/planningexternalevent.form.php?id=17?error=3 with insufficient rights. Additional information: User is missing the 1 (READ) right for planning
        Stack Trace:
                /var/www/html/glpi/src/Session.php:984 displayRightError()
                /var/www/html/glpi/front/planningexternalevent.form.php:38 checkRight()
2022-09-22 18:16:22 [15650@glpi-new]
User ID: 15650 tried to access or perform an action on /front/planningexternalevent.form.php?id=17 with insufficient rights. Additional information: User is missing the 1 (READ) right for planning
        Stack Trace:
                /var/www/html/glpi/src/Session.php:984 displayRightError()
                /var/www/html/glpi/front/planningexternalevent.form.php:38 checkRight()
2022-09-22 21:46:53 [4476@glpi-new]
User ID: 4476 tried to access or perform an action on /front/user.form.php?id=4476 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/user.form.php:241 displayFullPageForItem()
2022-09-23 10:39:11 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27262 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 10:40:29 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27237 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 10:46:39 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27203 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 14:17:58 [29221@glpi-new]
User ID: 29221 tried to access or perform an action on /front/user.form.php?id=29221 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/user.form.php:241 displayFullPageForItem()
2022-09-23 17:50:49 [7@glpi-new]
User ID: 7 tried to access a non-existent item /front/reminder.form.php?id=22. Additional information: The item could not be found in the database
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6270 displayNotFoundError()
                /var/www/html/glpi/src/CommonDBTM.php:6379 displayItemNotFoundPage()
                /var/www/html/glpi/front/reminder.form.php:143 displayFullPageForItem()
````

From the client side:
````
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '403' ('Forbidden'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.4.0</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReturnResponseHeaders>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<CreateNewEntity>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<Create>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()
````

**Comment by dxdemetriou** [comment]
Another one but I don't know if it's correct. On "Groups", it shouldn't be selected the "Task" for being able to count users when the "SEE SCHEDULE OF PEOPLE IN MY GROUPS" is selected? For example, I have a group "all" and "department" groups from LDAP with everything unchecked  except users, but it seems that currently there is no way to exclude them.

**Comment by dxdemetriou** [comment]
aw, ok, now I have seen that's a new feature for 10.1.0. So both of my issues (this and https://github.com/glpi-project/glpi/issues/12753) seems related with https://github.com/glpi-project/glpi/issues/12753
