### ISSUE TITLE
[GLPI 10.0.5] Filter Global Kaban on type is not working

### ISSUE THREAD

**Issue by MrYsson** [glpi-project/glpi#13593]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When we're on the Kanban containing all the projects and project tasks, the ``type`` filter doesn't work. We use the suggested options (``type`` then ``Project``). The other filters are working, at least ``title``, ``content``, ``team``, ``user`` and ``group``. So we tried combining these with the ``type`` filter, without success.

### Relevant log output

```shell
In the Browser's console (both Firefox and Opera):

Uncaught TypeError: Cannot read properties of undefined (reading 'raw')
    at SearchInput.makeTagEditable (SearchInput.js:491:28)
    at HTMLSpanElement.<anonymous> (SearchInput.js:354:18)
    at HTMLDivElement.dispatch (jquery.js:5430:1)
    at elemData.handle (jquery.js:5234:1)

in SearchInput.js:491
```

### Page URL

/front/project.form.php?showglobalkanban=1

### Steps To reproduce

1. With a super-admin user, and having projects and project tasks
2. Go to ``Tools > Projects``
3. Click on ``Global Kanban``
4. Check that you see both projects and tasks
5. Click on the filter bar and choose ``type``
6. Choose ``Project``
7. Issue : the tasks are still displayed

(doesn't work too with the type ``ProjectTask``)

### Your GLPI setup information

For security reasons, we'd like to limit the informations we share about the config. Plus, the issue seems to be on the client side. So here is a short version :
- Linux : 3.10
- PHP : 8.1.11
- Webserver : Apache2
- Plugins : all disabled

If you need more specific infos, just ask 😉

**Comment by MrYsson** [comment]
Thank you, I updated the same files as the commit in our test environnement and it works
