### ISSUE TITLE
Problem with composer.json  - build apereo/phpcas.

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#13750]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Problem with build apereo/phpcas.

Warning: file_get_contents(/var/www/vendor/glpi-project/inventory_format/lib/php/../../source_files/pci.ids): Failed to open stream: No such file or directory in /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php on line 205

Fatal error: Uncaught RuntimeException: Empty content in /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php:209

### Relevant log output

```shell
2023-01-05T10:49:03.0264892Z Step 7/57 : RUN curl --silent --show-error --fail --remote-name-all       https://raw.githubusercontent.com/glpi-project/glpi/${GLPI_VERSION}/composer.json       https://raw.githubusercontent.com/glpi-project/glpi/${GLPI_VERSION}/composer.lock     && COMPOSER_HOME=/tmp/composer composer require       --apcu-autoloader       --classmap-authoritative       --ignore-platform-reqs       --no-interaction       --no-progress       --no-suggest       --optimize-autoloader       --prefer-dist       --update-no-dev       --working-dir ${GLPI_PATHS_ROOT}       apereo/phpcas     && rm -fv composer.json
2023-01-05T10:49:03.0391029Z  ---> Running in ab6257ffa92e
2023-01-05T10:49:04.1119869Z [91mYou are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
2023-01-05T10:49:04.7303709Z [0m[91mInfo from https://repo.packagist.org: #StandWithUkraine
2023-01-05T10:49:04.7561543Z [0m[91m./composer.json has been updated
2023-01-05T10:49:04.9244083Z [0m[91mRunning composer update apereo/phpcas
2023-01-05T10:49:04.9314141Z [0m[91mLoading composer repositories with package information
2023-01-05T10:49:05.5676846Z [0m[91mUpdating dependencies
2023-01-05T10:49:05.5797490Z [0m[91mLock file operations: 1 install, 0 updates, 0 removals
2023-01-05T10:49:05.5800097Z [0m[91m  - Locking apereo/phpcas (1.6.0)
2023-01-05T10:49:05.5822782Z [0m[91mWriting lock file
2023-01-05T10:49:05.5825259Z [0m[91mInstalling dependencies from lock file
2023-01-05T10:49:05.5859020Z [0m[91mPackage operations: 1 install, 0 updates, 0 removals
2023-01-05T10:49:05.5866715Z [0m[91m  - Downloading apereo/phpcas (1.6.0)
2023-01-05T10:49:05.6493293Z [0m[91m  - Installing apereo/phpcas (1.6.0): Extracting archive
2023-01-05T10:49:05.8578279Z [0m[91mPackage container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
2023-01-05T10:49:05.8578788Z Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
2023-01-05T10:49:05.8579137Z Generating optimized autoload files
2023-01-05T10:49:07.5899604Z [0m[91m    Skipped installation of bin bin/sabredav for package sabre/dav: file not found in package
2023-01-05T10:49:07.5900091Z     Skipped installation of bin bin/naturalselection for package sabre/dav: file not found in package
2023-01-05T10:49:07.5900537Z     Skipped installation of bin bin/vobject for package sabre/vobject: file not found in package
2023-01-05T10:49:07.5900974Z     Skipped installation of bin bin/generate_vcards for package sabre/vobject: file not found in package
2023-01-05T10:49:07.5901491Z [0m[91m    Skipped installation of bin bin/pscss for package scssphp/scssphp: file not found in package
2023-01-05T10:49:07.5902014Z [0m[91m    Skipped installation of bin bin/jsonlint for package seld/jsonlint: file not found in package
2023-01-05T10:49:07.5902554Z [0m[91m    Skipped installation of bin bin/cam for package wapmorgan/unified-archive: file not found in package
2023-01-05T10:49:07.5902991Z [0m[91m39 packages you are using are looking for funding.
2023-01-05T10:49:07.5903578Z [0m[91mUse the `composer fund` command to find out more!
2023-01-05T10:49:07.7396239Z [0m[91m> @php -r "file_put_contents('.composer.hash', sha1_file('composer.lock'));"
2023-01-05T10:49:07.7550945Z [0m[91m> @php -f vendor/bin/build_hw_jsons
2023-01-05T10:49:07.7815501Z [0m
2023-01-05T10:49:07.7816314Z Warning: file_get_contents(/var/www/vendor/glpi-project/inventory_format/lib/php/../../source_files/pci.ids): Failed to open stream: No such file or directory in /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php on line 205
2023-01-05T10:49:07.7816733Z 
2023-01-05T10:49:07.7817107Z Fatal error: Uncaught RuntimeException: Empty content in /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php:209
2023-01-05T10:49:07.7817473Z Stack trace:
2023-01-05T10:49:07.7817958Z #0 /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php(227): Glpi\Inventory\FilesToJSON->getSourceFile('pciid')
2023-01-05T10:49:07.7818563Z #1 /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php(118): Glpi\Inventory\FilesToJSON->convertPciFile()
2023-01-05T10:49:07.7819356Z #2 /var/www/vendor/glpi-project/inventory_format/bin/build_hw_jsons(7): Glpi\Inventory\FilesToJSON->run()
2023-01-05T10:49:07.7819850Z #3 /var/www/vendor/bin/build_hw_jsons(120): include('/var/www/vendor...')
2023-01-05T10:49:07.7820114Z #4 {main}
2023-01-05T10:49:07.7820508Z   thrown in /var/www/vendor/glpi-project/inventory_format/lib/php/FilesToJSON.php on line 209
2023-01-05T10:49:07.7848006Z [91mScript @php -f vendor/bin/build_hw_jsons handling the post-update-cmd event returned with error code 255
```

**Comment by cedric-anne** [comment]
Hi,

It seems that you are trying to mix the release archive with an updated composer.json file. Release archive is cleaned to remove files that are useless on production environment. If you want to do such thing, you should remove the `vendor` directory and then use `composer install` to force fetching all vendor files.

**Comment by Wolvverine** [comment]
@cedric-anne 
Maybe in that case add apereo/phpcas to the standard GLPI build ?

**Comment by trasher** [comment]
see https://github.com/glpi-project/glpi/pull/13388
