### ISSUE TITLE
[9.2-RC2] Error while loading Email followups configuration

### ISSUE THREAD

**Issue by ejaecker** [glpi-project/glpi#2825]
Updated from 9.1.6 to 9.2RC2

Go to Setup/Notification/Email followup configuration and got that message :
![image](https://user-images.githubusercontent.com/26645521/30777686-ae7242ac-a0c0-11e7-98e4-f1ce70356971.png)

Here is PHP Log : 
```
PHP Fatal error:  Uncaught Error: Call to undefined function _() in C:\glpi-dev\inc\notificationmailingsetting.class.php:117
Stack trace:
#0 C:\glpi-dev\inc\notificationsetting.class.php(103): NotificationMailingSetting->showFormConfig()
#1 C:\glpi-dev\inc\commonglpi.class.php(482): NotificationSetting::displayTabContentForItem(Object(NotificationMailingSetting), '1', '')
#2 C:\glpi-dev\ajax\common.tabs.php(96): CommonGLPI::displayStandardTab(Object(NotificationMailingSetting), 'NotificationMai...', '', Array)
#3 {main}
  thrown in C:\glpi-dev\inc\notificationmailingsetting.class.php on line 117

```

**Comment by trasher** [comment]
It's been fixed in the 9.2 branch in PR https://github.com/glpi-project/glpi/pull/2795
