### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#460]
I just tested (local) merge from master of this branch to see if we can continue the work.
This error triggers on login : 
```log
on Feb 15 13:59:52.256244 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP Fatal error:  Class 'Glpi\\Toolbox' not found in /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/inc/event.class.php on line 82, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256432 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP Stack trace:, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256469 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP   1. {main}() /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/front/login.php:0, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256489 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP   2. Auth->Login() /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/front/login.php:78, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256507 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP   3. Glpi\\Event::log() /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/inc/auth.class.php:788, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256527 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP   4. CommonDBTM->add() /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/inc/event.class.php:111, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
[Mon Feb 15 13:59:52.256543 2016] [:error] [pid 3330:tid 140274537838336] [client 127.0.0.1:56136] FastCGI: server "/var/www/cgi-bin/php5.fcgi" stderr: PHP message: PHP   5. Glpi\\Event->post_addItem() /media/adelaunay/f8300cb9-ce6d-419c-bd74-5040e0102657/www/glpi/0.91-git/inc/commondbtm.class.php:837, referer: http://localhost/glpi/0.91-git/index.php?noAUTO=1
```

A suggestion ?

**Comment by remicollet** [comment]
I don't see any Toolbox usage in event.class.php 

But if you add one you need to add "use \Toolbox;" or directly call \Toolbox::logdebug(...)

**Comment by orthagh** [comment]
Thanks for the 'use \Toolbox', it fix the error

An additional error when executing phpunit from root path of glpi : 
```log
PHP Fatal error:  Uncaught exception 'Zend\I18n\Exception\InvalidArgumentException' with message 'Could not find or open file .../plugins/behaviors/locales/ for reading' in .../lib/Zend/I18n/Translator/Loader/Gettext.php:49
Stack trace:
#0 .../lib/Zend/I18n/Translator/Translator.php(700): Zend\I18n\Translator\Loader\Gettext->load('en_GB', '/media/adelauna...')
#1 .../lib/Zend/I18n/Translator/Translator.php(572): Zend\I18n\Translator\Translator->loadMessagesFromFiles('behaviors', 'en_GB')
#2 .../lib/Zend/I18n/Translator/Translator.php(440): Zend\I18n\Translator\Translator->loadMessages('behaviors', 'en_GB')
#3 .../lib/Zend/I18n in .../lib/Zend/I18n/Translator/Loader/Gettext.php on line 49
```

Any hints ?

**Comment by orthagh** [comment]
if i remove all plugins, no errors, but i don't any messages from phpunit command.

Is there a need to a special parameter for launch tests?

**Comment by orthagh** [comment]
Ok, i'm miss to recreate an empty 'plugin folder'.
Forget my last message

**Comment by orthagh** [comment]
Ok just found the issue.
CFG_GLPI isn't global and do not contains "languages" key when loading plugin gettext files

is use an intermediate boostrap file before include 'includes.php' to globalise CFG_GLPI.

I finally have a full test suite executed.
We have errors in sql-errors.log file due to faketable test, but it's minor
