### ISSUE TITLE
Upgrade fails because the default log dir isn't writeable

### ISSUE THREAD

**Issue by dani** [glpi-project/glpi#4676]
* Steps to reproduce (which actions have you made) :

Running GLPI 9.2.3 on CentOS 7 x86_64, with PHP 7.2 and MariaDB 10.3.9. I try to upgrade GLPI to 9.3.1 as usual (as I do since installation ~10 years ago ;-) ), but the test page is not complete

![glpi_test_page](https://user-images.githubusercontent.com/526826/45812416-094c1280-bcd0-11e8-89fc-b6d84f49a59b.png)

In my logs, I get this

```
sept. 20 12:24:33 web1.lapiole.org [18454]: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/opt/glpi_1/web/files/_log" and its not buildable: Permission denied in /opt/glpi_1/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:171
                                            Stack trace:
                                            #0 /opt/glpi_1/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
                                            #1 /opt/glpi_1/web/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
                                            #2 /opt/glpi_1/web/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
                                            #3 /opt/glpi_1/web/inc/toolbox.class.php(435): Monolog\Logger->addRecord(400, 'Toolbox::userEr...', Array)
                                            #4 /opt/glpi_1/web/inc/toolbox.class.php(469): Toolbox::log(Object(Monolog\Logger), 400, Array)
                                            #5 /opt/glpi_1/web/inc/toolbox.class.php(657): Toolbox::logError('  *** PHP Warni...')
                                            #6 [internal function]: Toolbox::userErrorHandlerNormal(2, 'file_exists(): ...', '/opt/glpi_1/web...' in /opt/glpi_1/web/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 171
```

/opt/glpi_1/web/ is indeed GLPI _ROOT_DIR, but I've configured logs to be stored in /opt/glpi_1/data/_log, see my config_path.php:
```
<?php

define("GLPI_DATA_DIR", "/opt/glpi_1/data");
define("GLPI_DOC_DIR", GLPI_DATA_DIR . "/_files");
define("GLPI_DUMP_DIR", GLPI_DATA_DIR . "/_dumps");
define("GLPI_CRON_DIR", GLPI_DATA_DIR . "/_cron");
define("GLPI_SESSION_DIR", "/opt/glpi_1/sessions");
define("GLPI_PLUGIN_DOC_DIR", GLPI_DATA_DIR . "/_plugins");
define("GLPI_LOCK_DIR", GLPI_DATA_DIR . "/_lock");
define("GLPI_LOG_DIR", GLPI_DATA_DIR . "/_log");
define("GLPI_GRAPH_DIR", GLPI_DATA_DIR . "/_graphs");
define("GLPI_PICTURE_DIR", GLPI_DATA_DIR . "/_pictures");
define("GLPI_TMP_DIR", "/opt/glpi_1/tmp");
define("GLPI_RSS_DIR", GLPI_DATA_DIR . "/_rss");
define("GLPI_UPLOAD_DIR", "/opt/glpi_1/tmp");
define("GLPI_CACHE_DIR", GLPI_DATA_DIR . "/_cache");

?>
```

So, GLPI_LOG_DIR is ignored at this point, and the app should backtrace, but instead just print nicely what is not writeable

* Expected result :
GLPI_LOG_DIR should be used, and the tests should be fine

* Actual result :
GLPI_LOG_DIR is ignored, the default location (ROOT/files/_log) doesn't exist (on purpose) and is not writeable, the app backtrace

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.2.4 ( => /opt/glpi_1/web) Installation mode: TARBALL

Operating system: Linux web1.lapiole.org 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 PHP 7.2.10 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, geoip, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, 	mbstring, mcrypt, memcached, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, 	session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, 	xmlwriter, xsl, zip, zlib) Setup: max_execution_time="60" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache () 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.9-MariaDB 	Server SQL Mode:  	Parameters: glpi_1@db.lapiole.org/glpi_1 	Host info: db.lapiole.org via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /opt/glpi_1/web/config : OK /opt/glpi_1/data/_files : OK /opt/glpi_1/data/_dumps : OK /opt/glpi_1/sessions : OK /opt/glpi_1/data/_cron : OK /opt/glpi_1/data/_graphs : OK /opt/glpi_1/data/_lock : OK /opt/glpi_1/data/_plugins : OK /opt/glpi_1/tmp : OK /opt/glpi_1/data/_cache : OK /opt/glpi_1/data/_rss : OK /opt/glpi_1/data/_pictures : OK /opt/glpi_1/data/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/opt/glpi_1/web/lib/htmlawed) phpCas version 1.3.5 in (/opt/glpi_1/web/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/opt/glpi_1/web/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/opt/glpi_1/web/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/opt/glpi_1/web/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/opt/glpi_1/web/vendor/michelf/php-markdown/Michelf) true/punycode in (/opt/glpi_1/web/vendor/true/punycode/src) iacaml/autolink in (/opt/glpi_1/web/vendor/iamcal/lib_autolink) sabre/vobject in (/opt/glpi_1/web/vendor/sabre/vobject/lib)

Not active

Way of sending emails: PHP

 

behaviors            Name: Comportements                  Version: 2.0.2      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.2+2.0    State: Enabled 	tag                  Name: Gestion des tags               Version: 2.1.0      State: Enabled 	pdf                  Name: Impression pdf                 Version: 1.3.1.1    State: Enabled 	reports              Name: Rapports                       Version: 1.11.3     State: Enabled


Informations sur le système, l'installation et la configuration
--
[code]   GLPI 9.2.4 ( => /opt/glpi_1/web) Installation mode: TARBALL

Operating system: Linux web1.lapiole.org 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 PHP 7.2.10 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, geoip, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, 	mbstring, mcrypt, memcached, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, 	session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, 	xmlwriter, xsl, zip, zlib) Setup: max_execution_time="60" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache () 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.9-MariaDB 	Server SQL Mode:  	Parameters: glpi_1@db.lapiole.org/glpi_1 	Host info: db.lapiole.org via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /opt/glpi_1/web/config : OK /opt/glpi_1/data/_files : OK /opt/glpi_1/data/_dumps : OK /opt/glpi_1/sessions : OK /opt/glpi_1/data/_cron : OK /opt/glpi_1/data/_graphs : OK /opt/glpi_1/data/_lock : OK /opt/glpi_1/data/_plugins : OK /opt/glpi_1/tmp : OK /opt/glpi_1/data/_cache : OK /opt/glpi_1/data/_rss : OK /opt/glpi_1/data/_pictures : OK /opt/glpi_1/data/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/opt/glpi_1/web/lib/htmlawed) phpCas version 1.3.5 in (/opt/glpi_1/web/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/opt/glpi_1/web/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/opt/glpi_1/web/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/opt/glpi_1/web/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/opt/glpi_1/web/vendor/michelf/php-markdown/Michelf) true/punycode in (/opt/glpi_1/web/vendor/true/punycode/src) iacaml/autolink in (/opt/glpi_1/web/vendor/iamcal/lib_autolink) sabre/vobject in (/opt/glpi_1/web/vendor/sabre/vobject/lib)

Not active

Way of sending emails: PHP

 

behaviors            Name: Comportements                  Version: 2.0.2      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.2+2.0    State: Enabled 	tag                  Name: Gestion des tags               Version: 2.1.0      State: Enabled 	pdf                  Name: Impression pdf                 Version: 1.3.1.1    State: Enabled 	reports              Name: Rapports                       Version: 1.11.3     State: Enabled
[/code]


```

**Comment by remicollet** [comment]
With 9.3 you need to use` local_define.php`

**Comment by dani** [comment]
Thanks, did the trick. I couldn't find this in any upgrade notes or anything

**Comment by trasher** [comment]
https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations
