### ISSUE TITLE
Error on Project Costs tab

### ISSUE THREAD

**Issue by neogorn** [glpi-project/glpi#5158]
Hi!

When I click on the Project -> Costs tab, the error "**An error occured loading contents!**" is displayed.

![image](https://user-images.githubusercontent.com/42190708/50343630-cdaf2780-050e-11e9-94da-80e3b843442f.png)

**Comment by trasher** [comment]
Hi,
When you create an issue, there is a template to follow. This template require you to copy paste logs, exactly what I'll ask you to provide now.

**Comment by neogorn** [comment]
> Hi,
> When you create an issue, there is a template to follow. This template require you to copy paste logs, exactly what I'll ask you to provide now.

Ok, sorry!

**Logs**

[cron.log](https://github.com/glpi-project/glpi/files/2702930/cron.log)
[event.log](https://github.com/glpi-project/glpi/files/2702931/event.log)
[migration_to_9.4.log](https://github.com/glpi-project/glpi/files/2702932/migration_to_9.4.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/2702933/php-errors.log)
[remove.txt](https://github.com/glpi-project/glpi/files/2702934/remove.txt)
[warning_during_migration_to_9.4.0@8970abe9a990dc2244e4d655bc6fcc4000d18fb0.log](https://github.com/glpi-project/glpi/files/2702936/warning_during_migration_to_9.4.0.8970abe9a990dc2244e4d655bc6fcc4000d18fb0.log)
[warning_during_migration_to_9.4.log](https://github.com/glpi-project/glpi/files/2702937/warning_during_migration_to_9.4.log)

**Comment by orthagh** [comment]
Hello @neogorn 

We need the content of the log files.
And if you could only track and extract the errors (with timestamp) relative to your issue, we'll be glad.

Thank you

**Comment by neogorn** [comment]
> Hello @neogorn
> 
> We need the content of the log files.
> And if you could only track and extract the errors (with timestamp) relative to your issue, we'll be glad.
> 
> Thank you

Hi, @orthagh.

In /var/log/httpd/error_log show this error. 

Does it help you?

**[Mon Jan 07 12:50:03.733603 2019] [:error] [pid 28450] [client 10.100.5.56:55568] PHP Fatal error:  Uncaught exception '           RuntimeException' with message 'Empty IN are not allowed' in /var/www/html/glpibeta/inc/dbmysqliterator.class.php:568\nS           tack trace:\n#0 /var/www/html/glpibeta/inc/dbmysqliterator.class.php(538): DBmysqlIterator->analyzeCriterion(Array)\n#1            /var/www/html/glpibeta/inc/dbmysqliterator.class.php(312): DBmysqlIterator->analyseCrit(Array)\n#2 /var/www/html/glpibet           a/inc/dbmysqliterator.class.php(94): DBmysqlIterator->buildQuery(Array, '', false)\n#3 /var/www/html/glpibeta/inc/dbmysq           l.class.php(562): DBmysqlIterator->execute(Array, '', false)\n#4 /var/www/html/glpibeta/inc/commonitilcost.class.php(494           ): DBmysql->request(Array)\n#5 /var/www/html/glpibeta/inc/projectcost.class.php(428): CommonITILCost::showForObject(Obje           ct(Project))\n#6 /var/www/html/glpibeta/inc/projectcost.class.php(108): ProjectCost::showForProject(Object(Project), '')           \n#7 /var/www/html/glpibeta/inc/commonglpi.class.php(485): ProjectCost::displayTabContentForItem(Object(Project), '1', '           ')\n#8 /var/www/html/glpibeta/ajax/common.tabs.php(92) in /var/www/html/glpibeta/inc/dbmysqliterator.class.php on line 5           68, referer: http://betaglpi.motiva/front/project.form.php?id=168**

Tks!

**Comment by trasher** [comment]
@neogorn could you please test proposed patch https://github.com/glpi-project/glpi/pull/5207? Thank you.

**Comment by neogorn** [comment]
> @neogorn could you please test proposed patch #5207? Thank you.

@trasher Patch #5207 solved!

Tks!
