### ISSUE TITLE
PHP Fatal error:  zendframework

### ISSUE THREAD

**Issue by picklesrein** [glpi-project/glpi#5429]
**Describe the bug**
Receiving error from cronjob:
`* * * * * /usr/bin/php /usr/share/glpi/front/cron.php`

```
PHP Fatal error:  Uncaught ErrorException: fopen(/usr/share/glpi/files/_cache/cache_db/zfcache-99/zfcache-table_of.dat): failed to open stream: Permission denied in /usr/share/glpi/vendor/zendframework/zend-cache/src/Storage/Adapter/Filesystem.php:1572
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(/usr/shar...', '/usr/share/glpi...', 1572, Array)
#1 /usr/share/glpi/vendor/zendframework/zend-cache/src/Storage/Adapter/Filesystem.php(1572): fopen('/usr/share/glpi...', 'cb')
#2 /usr/share/glpi/vendor/zendframework/zend-cache/src/Storage/Adapter/Filesystem.php(969): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('/usr/share/glpi...', 'a:1:{s:6:"Confi...', true, NULL)
#3 /usr/share/glpi/vendor/zendframework/zend-cache/src/Storage/Adapter/AbstractAdapter.php(688): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('table_of', 'a:1:{s:6:"Confi...')
#4 /usr/share/glpi/vendor/zendframework/zend-cache/src/Storage/Adapter/Filesystem.php(843): Zend\Cache\Storage\Adapter\AbstractAdapter->setIte in /usr/share/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php on line 300
```
**Logs**
cron.log:
```
[Cent-7:root@glpi_host ~]# tail /usr/share/glpi/files/_log/cron.log -n22
2019-02-20 10:04:01 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:05:02 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:06:01 [@glpi_host.my_domain.com]
External #1: Launch slaticket
2019-02-20 10:06:01 [@glpi_host.my_domain.com]
External #2: Launch planningrecall
2019-02-20 10:07:02 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:08:01 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:09:01 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:10:02 [@glpi_host.my_domain.com]
External #1: Nothing to launch
2019-02-20 10:11:02 [@glpi_host.my_domain.com]
External #1: Launch mailgate
2019-02-20 10:11:02 [@glpi_host.my_domain.com]
External #2: Launch slaticket
2019-02-20 10:11:02 [@glpi_host.my_domain.com]
External #3: Launch planningrecall
```
php-errors.log (though I'm not sure this is related to my error)
```
[Cent-7:root@glpi_host ~]# tail /usr/share/glpi/files/_log/php-errors.log
  *** PHP Notice(8): Undefined index: MEMORY
  Backtrace :
  ...usioninventory/inc/formatconvert.class.php:1373
  ...ry/inc/inventorycomputerinventory.class.php:170 PluginFusioninventoryFormatconvert::computerInventoryTransformation()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"6@glpi_host.my_domain.com"}
```

**Screenshots**

n/a

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.0 (/glpi => /usr/share/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux glpi_host.my_domain.com 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64
PHP 7.0.30 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, sockets,
	sqlite3, ssh2, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="4096M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.30 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.23
	Server SQL Mode: 
	Parameters: glpi_db_user@localhost/glpi_db
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
Database version seems correct (5.7.23) - Perfect!Database version seems correct (5.7.23) - Perfect!
OK/usr/share/glpi/files/_log : OK
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.6 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/usr/share/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-console in (/usr/share/glpi/vendor/zendframework/zend-console/src)
zendframework/zend-i18n in (/usr/share/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/usr/share/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
leafo/scssphp in (/usr/share/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.6 in (/usr/share/pear)

LDAP directories
 
Server: 'ns1.int.ad_domain.com', Port: '389', BaseDN: 'OU=Users - people,OU=Users - sorted,DC=int,DC=ad_domain,DC=com',
		Connection filter: '(&(objectClass=user)(objectCategory=person))', RootDN: none, Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled

```

**Additional context**

Noticed it by finding emails sent from apache@my_domain to apache@my_domain

**Comment by trasher** [comment]
`files` directory must be writeable from web server, this is checked at installl and update times (at least).
If you want to use cron, make sure to either st correct permissions on files directory, or use cron from apache user.

**Comment by picklesrein** [comment]
Very good. Thanks for the quick analysis. I chose the second option by moving the cronjob here:
`# crontab -eu apache`
Then corrected the permissions with:
`# chown -Rv apache: /usr/share/glpi/files/ | grep -v retained`

**Comment by trasher** [comment]
Yep, I guess this is the best choice ;)
