### ISSUE TITLE
Zend cache crash the mailcollector on subentity who exceed 64 car. path

### ISSUE THREAD

**Issue by mat44444** [glpi-project/glpi#6245]
**Describe the bug**

In GLPI 9.4.3,
Make a rule to assign a mailcollector to an sub-sub-entity, crash the collector process due to ZendCache Module.

When we look a the error this will append when the entity path exceed 64 characters

LOG:
```
[28-Aug-2019 21:44:53 America/New_York] PHP Fatal error:  Uncaught Zend\Cache\Psr\SimpleCache\SimpleCacheInvalidArgumentException: Invalid key "glpi_entities_ancestors_cache_Urgences-santÃ© &gt; DRI &gt; OpÃ©rations RI" provided; key is too long. Must be no more than 64 characters in /secret/html/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php:344
Stack trace:
#0 /secret/html/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php(279): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->validateKey('glpi_entities_a...')
#1 /secret/html/inc/cache/simplecache.class.php(147): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->has('glpi_entities_a...')
#2 /secret/html/inc/dbutils.class.php(789): Glpi\Cache\SimpleCache->has('glpi_entities_a...')
#3 /secret/html/inc/dbutils.class.php(639): DbUtils->getAncestorsOf('glpi_entities', 'Urgences-sant\xC3\xA9...')
#4 /opt/www/gri.dmz.ur in /secret/html/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php on line 344
```

**To reproduce**

1.Setup a mailcollector
2. Make some entities/sub entities who will exceed the 64 characters in path
3. Make a rule to assigne ticket to a sub entities whow exceed the 64 cars. path
4. See error 500

**Expected behavior**

Should work as espected

**Comment by trasher** [comment]
Fixed in https://github.com/glpi-project/glpi/pull/6076
