### ISSUE TITLE
Automatic action 'Mailgate' hangs as 'Running' into aleatory times

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#8836]
**Describe the bug**

After upgrading to GLPI 9.5.4, from time to time (aleatory), the automatic action 'mailgate' hangs with 'Running' state. This happens into aleatory times, even if there's no mail into the server for mailgate to download from. I believe this issue is somehow related to #8796 

**Page(s) URL**

https://glpi.example.com/front/crontask.form.php?id=9

**To reproduce**

1. Go to 'Configure' > 'Automatic Actions'
2. Click on 'mailgate'

**Expected behavior**

The mailgate automatic action should not hang, even if it ends with error.

**Logs**

Initially, it didn't reported any errors to the log when this error happens. After applying the #8773 and #8797 pull requests, the following error is being thrown into ``php-errors.log``:

php-errors.log:

```
[2021-03-14 07:51:06] glpiphplog.CRITICAL:   *** PHP Error (1): Uncaught ErrorException: fgets(): SSL: Connection reset by peer in /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol/Pop3.php:147
Stack trace:
#0 [internal function]: Laminas\Stdlib\ErrorHandler::addError(2, 'fgets(): SSL: C...', '/var/www/client...', 147, Array)
#1 /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol/Pop3.php(147): fgets(Resource id #266)
#2 /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol/Pop3.php(192): Laminas\Mail\Protocol\Pop3->readResponse(false)
#3 /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol/Pop3.php(258): Laminas\Mail\Protocol\Pop3->request('STAT')
#4 /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Storage/Pop3.php(34): Laminas\Mail\Protocol\Pop3->status(0, 0)
#5 /var/www/clients/client0/web1/web/inc/mailcollector.class.php(1476): Laminas\Mail\Storage\Pop3->countMessages()
#6 /var/www/clients/client0/web1/web/inc/mailcollector.class.php(713): MailCollector->getTota in /var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol/Pop3.php at line 150
```

No errors is being thrown into Apache logs (``error.log``  and ``access.log``), neither ``<GLPI_ROOT>\files\_log\sql-errors.log``.

**Screenshots**

![glpi example com_front_crontask form php_id=9](https://user-images.githubusercontent.com/2974895/111158073-614cf280-8576-11eb-8266-6d80d1c2b553.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]
 
GLPI 9.5.4 ( => /var/www/clients/client0/web1/web)
Installation mode: TARBALL

Server
 
Operating system: Linux ispconfig.example.com 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64
PHP 7.2.34 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="150 M" safe_mode="" session.save_handler="files"
	upload_max_filesize="150M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.27-MariaDB
	Server SQL Mode: 
	Parameters: c0glpiuser@localhost/c0glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.27) - Perfect!Database version seems correct (10.3.27) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/clients/client0/web1/web/files/_cache has been validated.Write access to /var/www/clients/client0/web1/web/files/_cache has been validated.
Write access to /var/www/clients/client0/web1/web/config has been validated.Write access to /var/www/clients/client0/web1/web/config has been validated.
Write access to /var/www/clients/client0/web1/web/files/_cron has been validated.Write access to /var/www/clients/client0/web1/web/files/_cron has been validated.
Write access to /var/www/clients/client0/web1/web/files has been validated.Write access to /var/www/clients/client0/web1/web/files has been validated.
Write access to /var/www/clients/client0/web1/web/files/_dumps has been validated.Write access to /var/www/clients/client0/web1/web/files/_dumps has been validated.
Write access to /var/www/clients/client0/web1/web/files/_graphs has been validated.Write access to /var/www/clients/client0/web1/web/files/_graphs has been validated.
Write access to /var/www/clients/client0/web1/web/files/_lock has been validated.Write access to /var/www/clients/client0/web1/web/files/_lock has been validated.
Write access to /var/www/clients/client0/web1/web/files/_pictures has been validated.Write access to /var/www/clients/client0/web1/web/files/_pictures has been validated.
Write access to /var/www/clients/client0/web1/web/files/_plugins has been validated.Write access to /var/www/clients/client0/web1/web/files/_plugins has been validated.
Write access to /var/www/clients/client0/web1/web/files/_rss has been validated.Write access to /var/www/clients/client0/web1/web/files/_rss has been validated.
Write access to /var/www/clients/client0/web1/web/files/_sessions has been validated.Write access to /var/www/clients/client0/web1/web/files/_sessions has been validated.
Write access to /var/www/clients/client0/web1/web/files/_tmp has been validated.Write access to /var/www/clients/client0/web1/web/files/_tmp has been validated.
Write access to /var/www/clients/client0/web1/web/files/_uploads has been validated.Write access to /var/www/clients/client0/web1/web/files/_uploads has been validated.
Write access to /var/www/clients/client0/web1/web/marketplace has been validated.Write access to /var/www/clients/client0/web1/web/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

GLPI constants
 
GLPI_ROOT: /var/www/clients/client0/web1/web
GLPI_CONFIG_DIR: /var/www/clients/client0/web1/web/config
GLPI_VAR_DIR: /var/www/clients/client0/web1/web/files
GLPI_MARKETPLACE_DIR: /var/www/clients/client0/web1/web/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/clients/client0/web1/web/files
GLPI_CACHE_DIR: /var/www/clients/client0/web1/web/files/_cache
GLPI_CRON_DIR: /var/www/clients/client0/web1/web/files/_cron
GLPI_DUMP_DIR: /var/www/clients/client0/web1/web/files/_dumps
GLPI_GRAPH_DIR: /var/www/clients/client0/web1/web/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/clients/client0/web1/web/files/_locales
GLPI_LOCK_DIR: /var/www/clients/client0/web1/web/files/_lock
GLPI_LOG_DIR: /var/www/clients/client0/web1/web/files/_log
GLPI_PICTURE_DIR: /var/www/clients/client0/web1/web/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/clients/client0/web1/web/files/_plugins
GLPI_RSS_DIR: /var/www/clients/client0/web1/web/files/_rss
GLPI_SESSION_DIR: /var/www/clients/client0/web1/web/files/_sessions
GLPI_TMP_DIR: /var/www/clients/client0/web1/web/files/_tmp
GLPI_UPLOAD_DIR: /var/www/clients/client0/web1/web/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/clients/client0/web1/web/locales
GLPI_VERSION: 9.5.4
GLPI_SCHEMA_VERSION: 9.5.4
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/clients/client0/web1/web/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/clients/client0/web1/web/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/clients/client0/web1/web/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/clients/client0/web1/web/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/clients/client0/web1/web/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/clients/client0/web1/web/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/clients/client0/web1/web/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/clients/client0/web1/web/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/clients/client0/web1/web/vendor/sabre/http/lib)
sabre/uri in (/var/www/clients/client0/web1/web/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/clients/client0/web1/web/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/clients/client0/web1/web/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/clients/client0/web1/web/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/clients/client0/web1/web/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/clients/client0/web1/web/vendor/symfony/console)
scssphp/scssphp in (/var/www/clients/client0/web1/web/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/clients/client0/web1/web/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/clients/client0/web1/web/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/clients/client0/web1/web/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/clients/client0/web1/web/vendor/ramsey/uuid/src)
psr/log in (/var/www/clients/client0/web1/web/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/clients/client0/web1/web/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/clients/client0/web1/web/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/clients/client0/web1/web/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/clients/client0/web1/web/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/clients/client0/web1/web/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/pear)

LDAP directories
 
Server: 'ldaps://example.com', Port: '389', BaseDN: 'OU=example,DC=example,DC=com,DC=br', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(memberOf=CN=Contas de Serviço -
		Negar Logon Interativo,OU=Serviços,OU=TI,OU=example,DC=example,DC=com,DC=br))(!(sAMAccountName=fabrica))(!(sAMAccountName=cq))(!(sAMAccountName=manutencao)))',
		RootDN: 'glpiaduser@example.com', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+SSL (glpi@example.com@smtp.kinghost.net)

Mails receivers
 
Name: 'glpi@example.com' Active: Yes
	Server: '{smtp.kinghost.net:995/pop/ssl/validate-cert}' Login: 'glpi@example.com' Password: Yes

Plugins list
 
	fields               Name: Campos adicionais              Version: 1.12.2     State: Enabled
	behaviors            Name: Comportamentos                 Version: 2.4.1      State: Enabled
	accounts             Name: Contas                         Version: 2.6.0      State: Enabled
	archimap             Name: Diagrams                       Version: 2.2.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+2.0  State: Enabled
	genericobject        Name: Gerenciamento de objetos       Version: 2.10.0     State: Installed / not activated
	manufacturersimports Name: Importação de fornecedores     Version: 2.3.1      State: Enabled
	pdf                  Name: Imprimir em PDF                Version: 1.7.0      State: Enabled
	mreporting           Name: Mais Relatórios                Version: 1.7.1      State: Enabled
	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled
	reports              Name: Relatórios                     Version: 1.14.0     State: Enabled
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled

[/code]
```

**Additional context**

I tried to execute the following command into the Linux terminal to see if there was any php/apache process running since 14-Mar-2021 07:51, but it didn't report any instance of these process running:

```
ps -eo pid,lstart,cmd
```

So I believe it's not a PHP bug loop problem. I believe that PHP is being executed and ending, but for some reason the lock for ``mailgate`` isn't being removed from database, since there's no lock file in ``<GLPI_ROOT>\files\_lock``. Maybe GLPI isn't handling PHPMailer exceptions properly and ending the script prematurely without releasing ``mailgate`` lock?

**Comment by cedric-anne** [comment]
Hi,

GLPI does not properly handle exception at all, except on some components that has been recently refactored. There is no global mechanism that handles exceptions on crontask, but it is something that should be done to prevent this behaviour.

Absence of this error handling is why the unlock task command has been created a long time ago, as a workaround. Documentation is available here : https://glpi-install.readthedocs.io/en/latest/command-line.html#task-unlock

Regards

**Comment by tomolimo** [comment]
Hello @eduardomozart 

Could you check the logs of the mailgate action itself (like below)?
![image](https://user-images.githubusercontent.com/7569958/111280382-0bdb1900-863c-11eb-9dac-e77b226e55dd.png)

Check around the time you mentioned (2021-03-14 07:51:06).

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello again @eduardomozart,

You may also check the Historical tab of the Receiver like below:
![image](https://user-images.githubusercontent.com/7569958/111280849-958ae680-863c-11eb-9af9-e0c69cd3b8ce.png)

Thank you
Regards,
Tomolimo

**Comment by eduardomozart** [comment]
Hello @tomolimo,
Thank you for your time.

**Mailgate Logs**

![mailgate-logs](https://user-images.githubusercontent.com/2974895/111293468-0ffd3b80-8628-11eb-9d5a-1ef4a7cae17d.png)

**Receivers Historical**

![receivers-historical](https://user-images.githubusercontent.com/2974895/111293460-0ecc0e80-8628-11eb-86c2-7721bdbe78cc.png)

It didn't show up any activities into the log anymore because I let the "mailgate" task into it's running to help to debug the issue, if it would be necessary.

Regards,
Eduardo Mozart.

**Comment by tomolimo** [comment]
Hello @eduardomozart 

You may see that your email server sometimes takes a long time to answer... up to >5s for an empty mailbox...

I can see the same behavior with a GLPI located in China using a mail server located in Frankfurt (DE). 
From times to times our email server didn't answer at all (this is shown by the connection errors) or it hangs on the communication (during an email transfer), and then in this case I could see that the mailgate is hanging in "running" status.

I've concluded that there are numerous network issues between email server (in Frankfurt) and GLPI (in China).

The solution I'm going to deploy, on the GLPI server, is a local mail relay ([hMailServer](https://www.hmailserver.com/)), for inbound emails (we are using IMAP in GLPI receiver, but the mail relay will use POP3 to get inbound emails from the mail server in Frankfurt).

Thank you,
Regards,
Tomolimo

**Comment by eduardomozart** [comment]
Hello tomolimo, thank you for your response. I was thinking about creating a crontask to cleanup mailgate hangup tasks or disabling SSL to test (not recommended), in fact, my mail provider sucks, and it's datacenter is less than 500KM from our HQ. I will give a look into implementing a mail relay, but I pretend to start a new job soon and I'm not sure if my successor will know how to mantain and troubleshoot it. Into an ideal world, even with delays, the cron_mailgate should handle exceptions like this to avoid getting the automatic action stuck, but I know it takes time to troubleshooting and debug issues like this and there's other priorities to the GLPI project, so I don't mind using an workaround for now.

**Comment by J-C-P** [comment]
Hi,
I'm having the same problem since 9.5.4 update a few days ago.
Did you find anything relevant or a fix for this ?
I have to unlock the task a few times per day.

Our mail provider is not far and looks quite reliable. We never had to complains about lag or disconnection.

**Comment by eduardomozart** [comment]
Hello @J-C-P,
I couldn't find any alternative solution. I didn't implement a mail relay yet, so I'm also unlocking the task a few times per day. You can automate the unlock through GLPI command line tools that you can run through Task Scheduler (Windows) or CRON (Unix). 
This problem also started to me after upgrading to GLPI 9.5.4, it was working fine before. So if no GLPI code changes was made, this error maybe related to some 3rd party library that is throwing a new kind of exception that the mailgate Automatic Action isn't handling. As @cedric-anne already stated, GLPI Automatic Actions has no error handling at all, so when mailgate throws an exception, it exits the automatic action without releasing the lock, so the automatic action hangs with 'Running' status and stops working. It starts working again after unlocking it and sync mails normally, but from time to time it hangs with no reason, so I need to unlock it manually from time to time.

**Comment by cedric-anne** [comment]
Hi,

Please consider upgrading to GLPI 9.5.5 (released yesterday).

In #8878, we changed the way crontask errors are handled. Now, when a task fails, the error should be logged correctly in `php-errors.log`, and task status should be put back to "waiting" state. If a task fails too many times (5 fails on last 10 executions), a notification will be sent (notification is configurable using `Automatic actions` itemtype and `Monitoring of automatic actions` event).

With this, you should be able to provide us an error stack trace, which can help us to investigate.

Regards

**Comment by eduardomozart** [comment]
I can confirm that after upgrading to GLPI 9.5.5, the problem is gone. When the mailgate task fails, it's throws an "Execution error" into the logs and is able to recover itself and running again successfully later instead of hanging the "mailgate" automatic action. Thank you @cedric-anne !
